### ISSUE TITLE
Allow an option to retest without a commit

### ISSUE THREAD

**Issue by gondoi** [harness/harness#107]
Some jobs could potentially run commands that do work remotely or require a re-run, but not necessarily require new code to be committed. It would be nice to have a redo type button on specific commit/pull requests.

**Comment by j** [comment]
Ugh.  @bradrydzewski clicking re-build is great and all, but if your repository has security set so that PRs have to be updated with the branch, you can click "Update Branch", and it doesn't trigger a re-build.

It'd be cool to be able to just comment and if the word "retest" exists, to re-fetch everything and start a new build.

**Comment by bradrydzewski** [comment]
Protected branches is a new feature from GitHub and has been evolving rapidly over the past few months and continues to evolve weekly. I'd recommend providing them with feedback that "Update Branch" should trigger a hook. It seems like it definitely should.
