### ISSUE TITLE
Different methods of authentication

### ISSUE THREAD

**Issue by floatdrop** [harness/harness#169]
Many companies have LDAP authentication protocol, so it would be very nice to have different authentication settings in drone like [github does](https://enterprise.github.com/help/articles/configuring-ldap-authentication).

**Comment by ahammond** [comment]
So, I live in the special hell reserved for those who run Stash / BitBucket Server. Our Stash instance uses LDAP for authentication. From what I've read, it sounds like I would create a user / password pair in LDAP, make that a super-user in Stash and then connect using that?

**Comment by JohnTheodore** [comment]
@ahammond did you figure out how to hook up drone.io to bitbucket in house? Did you have to do what you said, create an ldap super user ?

**Comment by ahammond** [comment]
I ended up building with Jenkins against a github repo. We are slowly
pushing people out of the legacy stash server and onto github.

**Comment by bradrydzewski** [comment]
> did you figure out how to hook up drone.io to bitbucket in house? Did you have to do what you said, create an ldap super user ?

stash does not require a super user account to login to the web interface. You can login with your regular stash account using oauth. Perhaps @josmo can clear this up

**Comment by josmo** [comment]
@JohnTheodore,  @bradrydzewski is correct. You don't need a single super user to log in. You should be able to login as any normal user.  You do need need a user that has git clone access to the repos (it's configuration required settings in Drone, but should be seamless to users) since stash doesn't support oauth clone access :( Lastly to enabled builds the user doing the first time enable of the repo does need to have access to set hooks on the repo.

**Comment by JohnTheodore** [comment]
@josmo I'm cross-posting from gitter (since this is indexed by google and I don't think gitter is).

I want to use drone.io's bitbucketserver for my entire project (there are dozens of repos in there, it's basically my business unit). I will talk to the bitbucketserver admin tomorrow about what's possible and check the admin UI (since I'm not a superadmin).

I think I can make a service account in bitbucket server that can read all my repos in my project through https? Though for the oauth2 application, my bitbucketserver admin turned off oauth2 for individual users. Can oauth2 stay off in general, but still be enable for a drone application (or the service user) that is scoped to only my project (without write permissions to modify git commits)? How granular are the oauth2 application settings for bitbucket server, do you know what the minimal settings are for it to work with your remote bitbucketserver setup?

any help/advice is appreciated.

**Comment by josmo** [comment]
@JohnTheodore I'll respond in gitter as well but to keep the history on it.

I don't believe Bitbucket server supports oauth2 I think it's only oauth1.  Right now the drone implementation is based on oauth1 so all you should need to do is add an application link and then anyone that has bitbucket server should be able to log in. I'm not familiar with disabling oauth for individual users so YMMV on that one.  You do need to setup a generic service account to be able to clone repos but that's not related to user auth just cloning for builds.

**Comment by JohnTheodore** [comment]
@josmo ok, oauth1 seems fine. Are there any permissions around oauth1? or is it just 'an oauth1 application' that has all the permissions or unknown permissions?

**Comment by josmo** [comment]
It's just an oauth1 application and the permissions will be those of the user that logs in.  A user enabling the repo needs to have hook creation access (I think its the admin role for a repo).

**Comment by JohnTheodore** [comment]
yea, that seems bad. I wish the oauth1 application only had permission to read repos and update the build pass/failed. it seems like bad security practice to give drone permission to write changes to the repo, when it's not needed. least privileges required so to speak. This is a limitation of bitbucketserver though, not the drone implementation.

**Comment by josmo** [comment]
I'm not sure I'm following. I do dislike the service account for cloning. However the auth is based on the access the user has. I guess it could be limited by the user on the stash side but can I'm not sure what that would really buy you security wise. Anyways let me know if you need more help. I know the integration is pretty solid and works well, minus some documentation and the fact that oauth1 makes some things less simple.

**Comment by JohnTheodore** [comment]
So you can give a user 'admin', 'write' or 'read' permission to a repo. If a user has admin privileges to a project or repo (or even just write), the drone bitbucketserver oauth1 token also has those admin privileges. so in theory drone could write changes to the repo, or delete a repo (although I know there is no code for this in the remote for bitbucketserver on drone). It would be nice if you could give the least privileges necessary for the user's oauth1 token, so it can only read and update the build pass/fail status

**Comment by josmo** [comment]
Well sadly that's a limitation of stash.

**Comment by JohnTheodore** [comment]
yep, agreed it's a limitation of stash(bitbucketserver).

It seems like Atlassian hasn't put nearly as much development effort into bitbucketserver as they have into bitbucket cloud. and based on the release notes, there is probably only one developer left doing stuff to it occasionally (a small change every couple months).
