### ISSUE TITLE
[Feature request] SSH Cloning

### ISSUE THREAD

**Issue by MarioGK-AutoSystem** [harness/harness#3392]
It would be great to clone the repositories using an SSH key instead of login and ~~password~~ api key

**Comment by avanmathur1** [comment]
@MarioGK-AutoSystem thanks for your feedback!  We will look into adding this support and keep you updated

**Comment by johannesHarness** [comment]
@MarioGK-AutoSystem wanted to provide some more context on this.
While GIT prompts a `username` and `password` during clone via `http/https`, we actually expect an API KEY to be provided as password, as it has limited lifetime and can be revoked. Your Gitness username + password won't actually work with git.
If you are being asked for the credentials on every pull/push, you can try to configure your git with a credentials manager, which will allow git to store the credentials for the domain locally and reuse them the next time.

This is similar to what Github is doing, where they explicitly disabled username + password credentials for git protocol due to security concerns (See they [blob post](https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/#background))

**Comment by MarioGK-AutoSystem** [comment]
> @MarioGK-AutoSystem wanted to provide some more context on this. While GIT prompts a `username` and `password` during clone via `http/https`, we actually expect an API KEY to be provided as password, as it has limited lifetime and can be revoked. Your Gitness username + password won't actually work with git. If you are being asked for the credentials on every pull/push, you can try to configure your git with a credentials manager, which will allow git to store the credentials for the domain locally and reuse them the next time.
> 
> This is similar to what Github is doing, where they explicitly disabled username + password credentials for git protocol due to security concerns (See they [blob post](https://github.blog/2020-07-30-token-authentication-requirements-for-api-and-git-operations/#background))

Edited my issue to say api key instead of password.

Yeah i think ssh keys are more convenient and safer than API keys for git operations

**Comment by sachaw** [comment]
This feature should be implemented along with commit signing validation. A user should be able to register ssh keys and mark them as authentication and/or signing keys

**Comment by yourfriendoss** [comment]
This seems to be a pretty big blocker to me as to why I won't use Gitness. SSH key verification and authenication would be perfect..

**Comment by mikekuzak** [comment]
+1
without SSH keys this is ```no bueno```

**Comment by pryorda** [comment]
Yeah.. No ssh or ssh over https is a no go :/

**Comment by notarock** [comment]
Is there an ETA for this? I would love to use gitness and that's this is a missing feature holding me back...

**Comment by kbaegis** [comment]
+1

This is not the opencore model you're looking for.

**Comment by pwolf-harness** [comment]
Hi, everyone. We appreciate the feedback and are actively working on adding SSH to Gitness to an upcoming release.

**Comment by cocoonkid** [comment]
Excellent. This is really missing.

**Comment by pwolf-harness** [comment]
This has been released in Harness Open Source.
