### ISSUE TITLE
Empty page after creating repository

### ISSUE THREAD

**Issue by matejkramny** [harness/harness#497]
After creating a repository in drone, users get a blank page..

It would be very useful to get a 'what next' kind of page, since every time i do it, it seems there's something wrong :P.

Also, in reference to #126, it would be good to initiate a build when there have been 0 builds. My drone sits on localhost and gitlab can't push to localhost.. Crafted a malicious POST which made drone pull a commit from gitlab., but could be more useful too

**Comment by robclancy** [comment]
Do you allow to start a build though? Seems weird to not have that. It should have been one of the very first features.

**Comment by tboerger** [comment]
> Do you allow to start a build though? Seems weird to not have that. It should have been one of the very first features.

That's simply not how drone works. Drone requires a webhook of github/gitlab/bitbucket/gogs to start an initial build. There is currently no way to start a build differently.

**Comment by robclancy** [comment]
Well that severely limits how drone can be used. We don't deploy every commit or a certain branch so deployment is off the table right away. Static site builders could also benefit greatly from drone but nope not with such a restriction "because drone doesn't work like that".

So something external can trigger whatever it likes but internally drone is just incapable of starting a build "because reasons"?

**Comment by tboerger** [comment]
Drone is totally tied to a git repository and in turn to get notified about changes to the above git hosting. So what do you expect?

**Comment by robclancy** [comment]
I use plenty of services tied to a git repository, some only to github, and they allow doing things by selecting a branch, tag and sometimes by hash. I _expect_ such a basic feature to exist which is why I came here, and I came here through multiple paths of people expecting the same thing. People don't ask for the feature added, they ask how to do it... because they expect it to possible in some form.

All good I'll just hack it in a fork or something if we choose this.

**Comment by bradrydzewski** [comment]
> Do you allow to start a build though? Seems weird to not have that. It should have been one of the very first features.

As mentioned above a build is started when you push to GitHub. This triggers a post-commit hook which is received by drone to execute the build. Generally speaking this is not an issue for most teams because upon activation you need to add a .drone.yml file, which triggers the very first build.

> Static site builders could also benefit greatly from drone but nope not with such a restriction "because drone doesn't work like that".

I use drone heavily with static site builders. Every post commit hook triggers a build in drone which executes the static site builder. I've then used the S3 plugin to push the static site to S3, I've used the rsync plugin to push to a server, and I've even used some custom shell commands to commit and push to gh_pages.

> So something external can trigger whatever it likes but internally drone is just incapable of starting a build "because reasons"?

You can restart an existing build using `drone restart` and `drone fork` commands. These can be used for things like nightly builds. This assumes, of course, that drone is building all commits and therefore every commit is in the database to re-build.

You can also manually invoke the `/hook` endpoint to trigger builds. You need to send a payload that exactly matches what GitHub would send, including some required HTTP headers and a per-repository token. This requires a bit more effort on your end, in terms of reverse engineering the payload, but it is certainly doable.

> We don't deploy every commit or a certain branch so deployment is off the table right away

Drone is built under the assumption that you are building every commit and testing every commit. We provide features that let you optionally trigger a deployment from an existing build. Let's say you push some code to master and it triggers a build. You don't want to deploy every push to master, but you decide you want to deploy this particular build. You can then run something like `drone deploy octocat/hello-world 55` where 55 is the build number you want deployed. In your yaml you can designate specific steps to run for deployments:

```yaml
build:
  setup:
    image: node
    commands:
    - npm install
  test:
    image: node
    commands:
    - npm test
    when:
     event: [ pull_request, push ]  # no need to run tests for deployments

deploy:
  npm:
    ...
    when:
      event: deployment # only run this step for deployment events
```

> People don't ask for the feature added, they ask how to do it

I agree, however, in this case it seems you've just asked for a feature. _how do I trigger a build?_ _It seems weird not to have this feature?_ Instead it is preferable that you provide use cases and what you are trying to achieve so we can advise how to do so within the constraints of this system.

I certainly don't appreciate having to take time away from writing code and improving drone to reply to this sort of thread making sweeping statements of what drone can and cannot do. If you have usage questions please ask in the [gitter room](https://gitter.im/drone/drone) and I'm sure people will be happy to offer suggestions and share details about their existing workflows.
