### ISSUE TITLE
401 (Unauthorized)  /api/user

### ISSUE THREAD

**Issue by ghost** [harness/harness#643]
I'm following the basic instructions for getting Drone up and running locally in an Ubuntu virtual machine. I manage to get to http://localhost:8080/install, but see nothing but the top bar with a link to /login, along with an HTTP error 401 when trying to access /api/user. When I click the login button I'm instructed to read the setup guide. I followed this guide once before and it seemed outdated.

I feel like I'm probably just missing something. Is there a stable version of Drone that corresponds exactly to a setup and install guide? I feel like the package version available at http://downloads.drone.io/master/drone.deb should always correspond exactly to the instructions at http://drone.readthedocs.org/en/latest/install.html. Though, it seems the .deb is the latest 0.3-dev version.

**Comment by MrMaxon** [comment]
Does this mean that your config file is wrong or missing a thing if you see a button that says "Read the Setup Guide"?

I have configured github client & secret as well as a the port and smtp, but all I see is that button. 

Where can I find the logs to see what's happening?

**Comment by bradrydzewski** [comment]
@MrMaxon I would double-check your configuration to ensure it matches the following docs:
http://readme.drone.io/setup/config/github/

I would also double check that you followed the official installation instructions since a lot of tutorials floating around on the web are really outdated and no longer valid:
http://readme.drone.io/setup/install/ubuntu/

Also be sure you are running the latest version of Drone:
http://downloads.drone.io/master/drone.deb

Lastly, be sure that when you make changes to the toml configuration file that you restart Drone. If you installed using Ubuntu the command is `sudo restart drone`

The log can be found at `/var/log/upstart/drone.log` but that assumes Drone has encountered an error to log. When Drone cannot parse the toml file, or if it finds an invalid value, it will exit immediately and dump a stack trace to the log.

**Comment by mrmaxon** [comment]
The log is empty :-/ 

The settings should be fine. I should have mentioned that I was using a Docker container. Guess I will use the Digital Ocean image for now :)

Would be nice to have an official Drone Docker image.

**Comment by dmcd** [comment]
I'm having the same issue when trying to run drone with the supplied Dockerfile. 
<img width="1434" alt="screen shot 2015-10-10 at 18 09 58" src="https://cloud.githubusercontent.com/assets/4025574/10409861/478f7fdc-6f7b-11e5-80e5-ad97357708bd.png">
