### ISSUE TITLE
When using drone cli disable command returns "Unauthorized"

### ISSUE THREAD

**Issue by miguel250** [harness/harness#721]
I was trying to disable a repository using the command `drone disable :host/:owner:/:name` but the command returns "Unauthorized". I don't think cli should go through authentication.

**Comment by engine07** [comment]
Hello,

I get weird behavior with drone cli when trying :
drone --token="my-auth-token" --server="http://my.drone.instance.com" whoami

every second time it returns : not authorized

same happens when doing request in browser : 
http://my.drone.instance.com/api/user/repos?access_token=TOKEN

when refreshing any page of drone gui in browser it works each time.
